SELECT p.ID AS NAME,
       DATE_PART('year', AGE(p.FINISH_DATE, p.START_DATE)) * 12 + DATE_PART('month', AGE(p.FINISH_DATE, p.START_DATE)) AS DURATION,
       SUM(w.SALARY) * (DATE_PART('year', AGE(p.FINISH_DATE, p.START_DATE)) * 12 + DATE_PART('month', AGE(p.FINISH_DATE, START_DATE))) AS PRICE
FROM project p
JOIN project_worker pw ON p.ID = pw.PROJECT_ID
JOIN worker w ON pw.WORKER_ID = w.ID
GROUP BY p.ID, p.START_DATE, p.FINISH_DATE
ORDER BY PRICE DESC;